#ifndef NF_FHIR_R4_H
#define NF_FHIR_R4_H

#define NF_NUM_RESOURCES 710
namespace native_fhir
{
	namespace nf_fhir_r4 {
		enum class ResourceType {
			Unknown,
			Resource,
			Account,
			Account_Coverage,
			Account_Guarantor,
			ActivityDefinition,
			ActivityDefinition_Participant,
			ActivityDefinition_DynamicValue,
			AdverseEvent,
			AdverseEvent_SuspectEntity,
			AdverseEvent_SuspectEntity_Causality,
			AllergyIntolerance,
			AllergyIntolerance_Reaction,
			Appointment,
			Appointment_Participant,
			AppointmentResponse,
			AuditEvent,
			AuditEvent_Agent,
			AuditEvent_Agent_Network,
			AuditEvent_Source,
			AuditEvent_Entity,
			AuditEvent_Entity_Detail,
			Basic,
			Binary,
			BiologicallyDerivedProduct,
			BiologicallyDerivedProduct_Collection,
			BiologicallyDerivedProduct_Processing,
			BiologicallyDerivedProduct_Manipulation,
			BiologicallyDerivedProduct_Storage,
			BodyStructure,
			Bundle,
			Bundle_Link,
			Bundle_Entry,
			Bundle_Entry_Search,
			Bundle_Entry_Request,
			Bundle_Entry_Response,
			CapabilityStatement,
			CapabilityStatement_Software,
			CapabilityStatement_Implementation,
			CapabilityStatement_Rest,
			CapabilityStatement_Rest_Security,
			CapabilityStatement_Rest_Resource,
			CapabilityStatement_Rest_Resource_Interaction,
			CapabilityStatement_Rest_Resource_SearchParam,
			CapabilityStatement_Rest_Resource_Operation,
			CapabilityStatement_Rest_Interaction,
			CapabilityStatement_Messaging,
			CapabilityStatement_Messaging_Endpoint,
			CapabilityStatement_Messaging_SupportedMessage,
			CapabilityStatement_Document,
			CarePlan,
			CarePlan_Activity,
			CarePlan_Activity_Detail,
			CareTeam,
			CareTeam_Participant,
			CatalogEntry,
			CatalogEntry_RelatedEntry,
			ChargeItem,
			ChargeItem_Performer,
			ChargeItemDefinition,
			ChargeItemDefinition_Applicability,
			ChargeItemDefinition_PropertyGroup,
			ChargeItemDefinition_PropertyGroup_PriceComponent,
			Claim,
			Claim_Related,
			Claim_Payee,
			Claim_CareTeam,
			Claim_SupportingInfo,
			Claim_Diagnosis,
			Claim_Procedure,
			Claim_Insurance,
			Claim_Accident,
			Claim_Item,
			Claim_Item_Detail,
			Claim_Item_Detail_SubDetail,
			ClaimResponse,
			ClaimResponse_Item,
			ClaimResponse_Item_Adjudication,
			ClaimResponse_Item_Detail,
			ClaimResponse_Item_Detail_SubDetail,
			ClaimResponse_AddItem,
			ClaimResponse_AddItem_Detail,
			ClaimResponse_AddItem_Detail_SubDetail,
			ClaimResponse_Total,
			ClaimResponse_Payment,
			ClaimResponse_ProcessNote,
			ClaimResponse_Insurance,
			ClaimResponse_Error,
			ClinicalImpression,
			ClinicalImpression_Investigation,
			ClinicalImpression_Finding,
			CodeSystem,
			CodeSystem_Filter,
			CodeSystem_Property,
			CodeSystem_Concept,
			CodeSystem_Concept_Designation,
			CodeSystem_Concept_Property,
			Communication,
			Communication_Payload,
			CommunicationRequest,
			CommunicationRequest_Payload,
			CompartmentDefinition,
			CompartmentDefinition_Resource,
			Composition,
			Composition_Attester,
			Composition_RelatesTo,
			Composition_Event,
			Composition_Section,
			ConceptMap,
			ConceptMap_Group,
			ConceptMap_Group_Element,
			ConceptMap_Group_Element_Target,
			ConceptMap_Group_Element_Target_DependsOn,
			ConceptMap_Group_Unmapped,
			Condition,
			Condition_Stage,
			Condition_Evidence,
			Consent,
			Consent_Policy,
			Consent_Verification,
			Consent_Provision,
			Consent_Provision_Actor,
			Consent_Provision_Data,
			Contract,
			Contract_ContentDefinition,
			Contract_Term,
			Contract_Term_SecurityLabel,
			Contract_Term_Offer,
			Contract_Term_Offer_Party,
			Contract_Term_Offer_Answer,
			Contract_Term_Asset,
			Contract_Term_Asset_Context,
			Contract_Term_Asset_ValuedItem,
			Contract_Term_Action,
			Contract_Term_Action_Subject,
			Contract_Signer,
			Contract_Friendly,
			Contract_Legal,
			Contract_Rule,
			Coverage,
			Coverage_Class,
			Coverage_CostToBeneficiary,
			Coverage_CostToBeneficiary_Exception,
			CoverageEligibilityRequest,
			CoverageEligibilityRequest_SupportingInfo,
			CoverageEligibilityRequest_Insurance,
			CoverageEligibilityRequest_Item,
			CoverageEligibilityRequest_Item_Diagnosis,
			CoverageEligibilityResponse,
			CoverageEligibilityResponse_Insurance,
			CoverageEligibilityResponse_Insurance_Item,
			CoverageEligibilityResponse_Insurance_Item_Benefit,
			CoverageEligibilityResponse_Error,
			DetectedIssue,
			DetectedIssue_Evidence,
			DetectedIssue_Mitigation,
			Device,
			Device_UdiCarrier,
			Device_DeviceName,
			Device_Specialization,
			Device_Version,
			Device_Property,
			DeviceDefinition,
			DeviceDefinition_UdiDeviceIdentifier,
			DeviceDefinition_DeviceName,
			DeviceDefinition_Specialization,
			DeviceDefinition_Capability,
			DeviceDefinition_Property,
			DeviceDefinition_Material,
			DeviceMetric,
			DeviceMetric_Calibration,
			DeviceRequest,
			DeviceRequest_Parameter,
			DeviceUseStatement,
			DiagnosticReport,
			DiagnosticReport_Media,
			DocumentManifest,
			DocumentManifest_Related,
			DocumentReference,
			DocumentReference_RelatesTo,
			DocumentReference_Content,
			DocumentReference_Context,
			DomainResource,
			EffectEvidenceSynthesis,
			EffectEvidenceSynthesis_SampleSize,
			EffectEvidenceSynthesis_ResultsByExposure,
			EffectEvidenceSynthesis_EffectEstimate,
			EffectEvidenceSynthesis_EffectEstimate_PrecisionEstimate,
			EffectEvidenceSynthesis_Certainty,
			EffectEvidenceSynthesis_Certainty_CertaintySubcomponent,
			Encounter,
			Encounter_StatusHistory,
			Encounter_ClassHistory,
			Encounter_Participant,
			Encounter_Diagnosis,
			Encounter_Hospitalization,
			Encounter_Location,
			Endpoint,
			EnrollmentRequest,
			EnrollmentResponse,
			EpisodeOfCare,
			EpisodeOfCare_StatusHistory,
			EpisodeOfCare_Diagnosis,
			EventDefinition,
			Evidence,
			EvidenceVariable,
			EvidenceVariable_Characteristic,
			ExampleScenario,
			ExampleScenario_Actor,
			ExampleScenario_Instance,
			ExampleScenario_Instance_Version,
			ExampleScenario_Instance_ContainedInstance,
			ExampleScenario_Process,
			ExampleScenario_Process_Step,
			ExampleScenario_Process_Step_Operation,
			ExampleScenario_Process_Step_Alternative,
			ExplanationOfBenefit,
			ExplanationOfBenefit_Related,
			ExplanationOfBenefit_Payee,
			ExplanationOfBenefit_CareTeam,
			ExplanationOfBenefit_SupportingInfo,
			ExplanationOfBenefit_Diagnosis,
			ExplanationOfBenefit_Procedure,
			ExplanationOfBenefit_Insurance,
			ExplanationOfBenefit_Accident,
			ExplanationOfBenefit_Item,
			ExplanationOfBenefit_Item_Adjudication,
			ExplanationOfBenefit_Item_Detail,
			ExplanationOfBenefit_Item_Detail_SubDetail,
			ExplanationOfBenefit_AddItem,
			ExplanationOfBenefit_AddItem_Detail,
			ExplanationOfBenefit_AddItem_Detail_SubDetail,
			ExplanationOfBenefit_Total,
			ExplanationOfBenefit_Payment,
			ExplanationOfBenefit_ProcessNote,
			ExplanationOfBenefit_BenefitBalance,
			ExplanationOfBenefit_BenefitBalance_Financial,
			FamilyMemberHistory,
			FamilyMemberHistory_Condition,
			Flag,
			Goal,
			Goal_Target,
			GraphDefinition,
			GraphDefinition_Link,
			GraphDefinition_Link_Target,
			GraphDefinition_Link_Target_Compartment,
			Group,
			Group_Characteristic,
			Group_Member,
			GuidanceResponse,
			HealthcareService,
			HealthcareService_Eligibility,
			HealthcareService_AvailableTime,
			HealthcareService_NotAvailable,
			ImagingStudy,
			ImagingStudy_Series,
			ImagingStudy_Series_Performer,
			ImagingStudy_Series_Instance,
			Immunization,
			Immunization_Performer,
			Immunization_Education,
			Immunization_Reaction,
			Immunization_ProtocolApplied,
			ImmunizationEvaluation,
			ImmunizationRecommendation,
			ImmunizationRecommendation_Recommendation,
			ImmunizationRecommendation_Recommendation_DateCriterion,
			ImplementationGuide,
			ImplementationGuide_DependsOn,
			ImplementationGuide_Global,
			ImplementationGuide_Definition,
			ImplementationGuide_Definition_Grouping,
			ImplementationGuide_Definition_Resource,
			ImplementationGuide_Definition_Page,
			ImplementationGuide_Definition_Parameter,
			ImplementationGuide_Definition_Template,
			ImplementationGuide_Manifest,
			ImplementationGuide_Manifest_Resource,
			ImplementationGuide_Manifest_Page,
			InsurancePlan,
			InsurancePlan_Contact,
			InsurancePlan_Coverage,
			InsurancePlan_Coverage_Benefit,
			InsurancePlan_Coverage_Benefit_Limit,
			InsurancePlan_Plan,
			InsurancePlan_Plan_GeneralCost,
			InsurancePlan_Plan_SpecificCost,
			InsurancePlan_Plan_SpecificCost_Benefit,
			InsurancePlan_Plan_SpecificCost_Benefit_Cost,
			Invoice,
			Invoice_Participant,
			Invoice_LineItem,
			Invoice_LineItem_PriceComponent,
			Library,
			Linkage,
			Linkage_Item,
			List,
			List_Entry,
			Location,
			Location_Position,
			Location_HoursOfOperation,
			Measure,
			Measure_Group,
			Measure_Group_Population,
			Measure_Group_Stratifier,
			Measure_Group_Stratifier_Component,
			Measure_SupplementalData,
			MeasureReport,
			MeasureReport_Group,
			MeasureReport_Group_Population,
			MeasureReport_Group_Stratifier,
			MeasureReport_Group_Stratifier_Stratum,
			MeasureReport_Group_Stratifier_Stratum_Component,
			MeasureReport_Group_Stratifier_Stratum_Population,
			Media,
			Medication,
			Medication_Ingredient,
			Medication_Batch,
			MedicationAdministration,
			MedicationAdministration_Performer,
			MedicationAdministration_Dosage,
			MedicationDispense,
			MedicationDispense_Performer,
			MedicationDispense_Substitution,
			MedicationKnowledge,
			MedicationKnowledge_RelatedMedicationKnowledge,
			MedicationKnowledge_Monograph,
			MedicationKnowledge_Ingredient,
			MedicationKnowledge_Cost,
			MedicationKnowledge_MonitoringProgram,
			MedicationKnowledge_AdministrationGuidelines,
			MedicationKnowledge_AdministrationGuidelines_Dosage,
			MedicationKnowledge_AdministrationGuidelines_PatientCharacteristics,
			MedicationKnowledge_MedicineClassification,
			MedicationKnowledge_Packaging,
			MedicationKnowledge_DrugCharacteristic,
			MedicationKnowledge_Regulatory,
			MedicationKnowledge_Regulatory_Substitution,
			MedicationKnowledge_Regulatory_Schedule,
			MedicationKnowledge_Regulatory_MaxDispense,
			MedicationKnowledge_Kinetics,
			MedicationRequest,
			MedicationRequest_DispenseRequest,
			MedicationRequest_DispenseRequest_InitialFill,
			MedicationRequest_Substitution,
			MedicationStatement,
			MedicinalProduct,
			MedicinalProduct_Name,
			MedicinalProduct_Name_NamePart,
			MedicinalProduct_Name_CountryLanguage,
			MedicinalProduct_ManufacturingBusinessOperation,
			MedicinalProduct_SpecialDesignation,
			MedicinalProductAuthorization,
			MedicinalProductAuthorization_JurisdictionalAuthorization,
			MedicinalProductAuthorization_Procedure,
			MedicinalProductContraindication,
			MedicinalProductContraindication_OtherTherapy,
			MedicinalProductIndication,
			MedicinalProductIndication_OtherTherapy,
			MedicinalProductIngredient,
			MedicinalProductIngredient_SpecifiedSubstance,
			MedicinalProductIngredient_SpecifiedSubstance_Strength,
			MedicinalProductIngredient_SpecifiedSubstance_Strength_ReferenceStrength,
			MedicinalProductIngredient_Substance,
			MedicinalProductInteraction,
			MedicinalProductInteraction_Interactant,
			MedicinalProductManufactured,
			MedicinalProductPackaged,
			MedicinalProductPackaged_BatchIdentifier,
			MedicinalProductPackaged_PackageItem,
			MedicinalProductPharmaceutical,
			MedicinalProductPharmaceutical_Characteristics,
			MedicinalProductPharmaceutical_RouteOfAdministration,
			MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies,
			MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies_WithdrawalPeriod,
			MedicinalProductUndesirableEffect,
			MessageDefinition,
			MessageDefinition_Focus,
			MessageDefinition_AllowedResponse,
			MessageHeader,
			MessageHeader_Destination,
			MessageHeader_Source,
			MessageHeader_Response,
			MolecularSequence,
			MolecularSequence_ReferenceSeq,
			MolecularSequence_Variant,
			MolecularSequence_Quality,
			MolecularSequence_Quality_Roc,
			MolecularSequence_Repository,
			MolecularSequence_StructureVariant,
			MolecularSequence_StructureVariant_Outer,
			MolecularSequence_StructureVariant_Inner,
			NamingSystem,
			NamingSystem_UniqueId,
			NutritionOrder,
			NutritionOrder_OralDiet,
			NutritionOrder_OralDiet_Nutrient,
			NutritionOrder_OralDiet_Texture,
			NutritionOrder_Supplement,
			NutritionOrder_EnteralFormula,
			NutritionOrder_EnteralFormula_Administration,
			Observation,
			Observation_ReferenceRange,
			Observation_Component,
			ObservationDefinition,
			ObservationDefinition_QuantitativeDetails,
			ObservationDefinition_QualifiedInterval,
			OperationDefinition,
			OperationDefinition_Parameter,
			OperationDefinition_Parameter_Binding,
			OperationDefinition_Parameter_ReferencedFrom,
			OperationDefinition_Overload,
			OperationOutcome,
			OperationOutcome_Issue,
			Organization,
			Organization_Contact,
			OrganizationAffiliation,
			Parameters,
			Parameters_Parameter,
			Patient,
			Patient_Contact,
			Patient_Communication,
			Patient_Link,
			PaymentNotice,
			PaymentReconciliation,
			PaymentReconciliation_Detail,
			PaymentReconciliation_ProcessNote,
			Person,
			Person_Link,
			PlanDefinition,
			PlanDefinition_Goal,
			PlanDefinition_Goal_Target,
			PlanDefinition_Action,
			PlanDefinition_Action_Condition,
			PlanDefinition_Action_RelatedAction,
			PlanDefinition_Action_Participant,
			PlanDefinition_Action_DynamicValue,
			Practitioner,
			Practitioner_Qualification,
			PractitionerRole,
			PractitionerRole_AvailableTime,
			PractitionerRole_NotAvailable,
			Procedure,
			Procedure_Performer,
			Procedure_FocalDevice,
			Provenance,
			Provenance_Agent,
			Provenance_Entity,
			Questionnaire,
			Questionnaire_Item,
			Questionnaire_Item_EnableWhen,
			Questionnaire_Item_AnswerOption,
			Questionnaire_Item_Initial,
			QuestionnaireResponse,
			QuestionnaireResponse_Item,
			QuestionnaireResponse_Item_Answer,
			RelatedPerson,
			RelatedPerson_Communication,
			RequestGroup,
			RequestGroup_Action,
			RequestGroup_Action_Condition,
			RequestGroup_Action_RelatedAction,
			ResearchDefinition,
			ResearchElementDefinition,
			ResearchElementDefinition_Characteristic,
			ResearchStudy,
			ResearchStudy_Arm,
			ResearchStudy_Objective,
			ResearchSubject,
			RiskAssessment,
			RiskAssessment_Prediction,
			RiskEvidenceSynthesis,
			RiskEvidenceSynthesis_SampleSize,
			RiskEvidenceSynthesis_RiskEstimate,
			RiskEvidenceSynthesis_RiskEstimate_PrecisionEstimate,
			RiskEvidenceSynthesis_Certainty,
			RiskEvidenceSynthesis_Certainty_CertaintySubcomponent,
			Schedule,
			SearchParameter,
			SearchParameter_Component,
			ServiceRequest,
			Slot,
			Specimen,
			Specimen_Collection,
			Specimen_Processing,
			Specimen_Container,
			SpecimenDefinition,
			SpecimenDefinition_TypeTested,
			SpecimenDefinition_TypeTested_Container,
			SpecimenDefinition_TypeTested_Container_Additive,
			SpecimenDefinition_TypeTested_Handling,
			StructureDefinition,
			StructureDefinition_Mapping,
			StructureDefinition_Context,
			StructureDefinition_Snapshot,
			StructureDefinition_Differential,
			StructureMap,
			StructureMap_Structure,
			StructureMap_Group,
			StructureMap_Group_Input,
			StructureMap_Group_Rule,
			StructureMap_Group_Rule_Source,
			StructureMap_Group_Rule_Target,
			StructureMap_Group_Rule_Target_Parameter,
			StructureMap_Group_Rule_Dependent,
			Subscription,
			Subscription_Channel,
			Substance,
			Substance_Instance,
			Substance_Ingredient,
			SubstanceNucleicAcid,
			SubstanceNucleicAcid_Subunit,
			SubstanceNucleicAcid_Subunit_Linkage,
			SubstanceNucleicAcid_Subunit_Sugar,
			SubstancePolymer,
			SubstancePolymer_MonomerSet,
			SubstancePolymer_MonomerSet_StartingMaterial,
			SubstancePolymer_Repeat,
			SubstancePolymer_Repeat_RepeatUnit,
			SubstancePolymer_Repeat_RepeatUnit_DegreeOfPolymerisation,
			SubstancePolymer_Repeat_RepeatUnit_StructuralRepresentation,
			SubstanceProtein,
			SubstanceProtein_Subunit,
			SubstanceReferenceInformation,
			SubstanceReferenceInformation_Gene,
			SubstanceReferenceInformation_GeneElement,
			SubstanceReferenceInformation_Classification,
			SubstanceReferenceInformation_Target,
			SubstanceSourceMaterial,
			SubstanceSourceMaterial_FractionDescription,
			SubstanceSourceMaterial_Organism,
			SubstanceSourceMaterial_Organism_Author,
			SubstanceSourceMaterial_Organism_Hybrid,
			SubstanceSourceMaterial_Organism_OrganismGeneral,
			SubstanceSourceMaterial_PartDescription,
			SubstanceSpecification,
			SubstanceSpecification_Moiety,
			SubstanceSpecification_Property,
			SubstanceSpecification_Structure,
			SubstanceSpecification_Structure_Isotope,
			SubstanceSpecification_Structure_Isotope_MolecularWeight,
			SubstanceSpecification_Structure_Representation,
			SubstanceSpecification_Code,
			SubstanceSpecification_Name,
			SubstanceSpecification_Name_Official,
			SubstanceSpecification_Relationship,
			SupplyDelivery,
			SupplyDelivery_SuppliedItem,
			SupplyRequest,
			SupplyRequest_Parameter,
			Task,
			Task_Restriction,
			Task_Input,
			Task_Output,
			TerminologyCapabilities,
			TerminologyCapabilities_Software,
			TerminologyCapabilities_Implementation,
			TerminologyCapabilities_CodeSystem,
			TerminologyCapabilities_CodeSystem_Version,
			TerminologyCapabilities_CodeSystem_Version_Filter,
			TerminologyCapabilities_Expansion,
			TerminologyCapabilities_Expansion_Parameter,
			TerminologyCapabilities_ValidateCode,
			TerminologyCapabilities_Translation,
			TerminologyCapabilities_Closure,
			TestReport,
			TestReport_Participant,
			TestReport_Setup,
			TestReport_Setup_Action,
			TestReport_Setup_Action_Operation,
			TestReport_Setup_Action_Assert,
			TestReport_Test,
			TestReport_Test_Action,
			TestReport_Teardown,
			TestReport_Teardown_Action,
			TestScript,
			TestScript_Origin,
			TestScript_Destination,
			TestScript_Metadata,
			TestScript_Metadata_Link,
			TestScript_Metadata_Capability,
			TestScript_Fixture,
			TestScript_Variable,
			TestScript_Setup,
			TestScript_Setup_Action,
			TestScript_Setup_Action_Operation,
			TestScript_Setup_Action_Operation_RequestHeader,
			TestScript_Setup_Action_Assert,
			TestScript_Test,
			TestScript_Test_Action,
			TestScript_Teardown,
			TestScript_Teardown_Action,
			ValueSet,
			ValueSet_Compose,
			ValueSet_Compose_Include,
			ValueSet_Compose_Include_Concept,
			ValueSet_Compose_Include_Concept_Designation,
			ValueSet_Compose_Include_Filter,
			ValueSet_Expansion,
			ValueSet_Expansion_Parameter,
			ValueSet_Expansion_Contains,
			VerificationResult,
			VerificationResult_PrimarySource,
			VerificationResult_Attestation,
			VerificationResult_Validator,
			VisionPrescription,
			VisionPrescription_LensSpecification,
			VisionPrescription_LensSpecification_Prism,
			MetadataResource,
			Element,
			BackboneElement,
			Address,
			Age,
			Annotation,
			Attachment,
			CodeableConcept,
			Coding,
			ContactDetail,
			ContactPoint,
			Contributor,
			Count,
			DataRequirement,
			DataRequirement_CodeFilter,
			DataRequirement_DateFilter,
			DataRequirement_Sort,
			Distance,
			Dosage,
			Dosage_DoseAndRate,
			Duration,
			ElementDefinition,
			ElementDefinition_Slicing,
			ElementDefinition_Slicing_Discriminator,
			ElementDefinition_Base,
			ElementDefinition_Type,
			ElementDefinition_Example,
			ElementDefinition_Constraint,
			ElementDefinition_Binding,
			ElementDefinition_Mapping,
			Expression,
			Extension,
			HumanName,
			Identifier,
			MarketingStatus,
			Meta,
			Money,
			Narrative,
			ParameterDefinition,
			Period,
			Population,
			ProdCharacteristic,
			ProductShelfLife,
			Quantity,
			Range,
			Ratio,
			Reference,
			RelatedArtifact,
			SampledData,
			Signature,
			SubstanceAmount,
			SubstanceAmount_ReferenceRange,
			Timing,
			Timing_Repeat,
			TriggerDefinition,
			UsageContext,
			MoneyQuantity,
			SimpleQuantity,
			Shareablemeasure,
			Servicerequest_genetics,
			Groupdefinition,
			Actualgroup,
			Familymemberhistory_genetic,
			Shareableactivitydefinition,
			Cdshooksrequestgroup,
			Provenance_relevant_history,
			Cqf_questionnaire,
			Shareablevalueset,
			Picoelement,
			Shareablecodesystem,
			Cdshooksguidanceresponse,
			Devicemetricobservation,
			Observation_genetics,
			Vitalsigns,
			Bodyweight,
			Vitalspanel,
			Bodyheight,
			Resprate,
			Heartrate,
			Bodytemp,
			Headcircum,
			Oxygensat,
			Bmi,
			Bp,
			Shareablelibrary,
			Cqllibrary,
			Lipidprofile,
			Cholesterol,
			Triglyceride,
			Hdlcholesterol,
			Ldlcholesterol,
			Diagnosticreport_genetics,
			Hlaresult,
			Synthesis,
			Clinicaldocument,
			Catalog,
			Shareableplandefinition,
			Computableplandefinition,
			Cdshooksserviceplandefinition,
			Elementdefinition_de,
			Ehrsrle_auditevent,
			Ehrsrle_provenance
		};

		typedef struct ResourceTypeString8Pair {
			ResourceType type;
			String8 str;
		} ResourceTypeString8Pair;
    
		ResourceTypeString8Pair resource_type_pairs[] = {
			{ ResourceType::Unknown, Str8Lit("Unknown") },
			{ ResourceType::Resource, Str8Lit("Resource") },
			{ ResourceType::Account, Str8Lit("Account") },
			{ ResourceType::Account_Coverage, Str8Lit("Account_Coverage") },
			{ ResourceType::Account_Guarantor, Str8Lit("Account_Guarantor") },
			{ ResourceType::ActivityDefinition, Str8Lit("ActivityDefinition") },
			{ ResourceType::ActivityDefinition_Participant, Str8Lit("ActivityDefinition_Participant") },
			{ ResourceType::ActivityDefinition_DynamicValue, Str8Lit("ActivityDefinition_DynamicValue") },
			{ ResourceType::AdverseEvent, Str8Lit("AdverseEvent") },
			{ ResourceType::AdverseEvent_SuspectEntity, Str8Lit("AdverseEvent_SuspectEntity") },
			{ ResourceType::AdverseEvent_SuspectEntity_Causality, Str8Lit("AdverseEvent_SuspectEntity_Causality") },
			{ ResourceType::AllergyIntolerance, Str8Lit("AllergyIntolerance") },
			{ ResourceType::AllergyIntolerance_Reaction, Str8Lit("AllergyIntolerance_Reaction") },
			{ ResourceType::Appointment, Str8Lit("Appointment") },
			{ ResourceType::Appointment_Participant, Str8Lit("Appointment_Participant") },
			{ ResourceType::AppointmentResponse, Str8Lit("AppointmentResponse") },
			{ ResourceType::AuditEvent, Str8Lit("AuditEvent") },
			{ ResourceType::AuditEvent_Agent, Str8Lit("AuditEvent_Agent") },
			{ ResourceType::AuditEvent_Agent_Network, Str8Lit("AuditEvent_Agent_Network") },
			{ ResourceType::AuditEvent_Source, Str8Lit("AuditEvent_Source") },
			{ ResourceType::AuditEvent_Entity, Str8Lit("AuditEvent_Entity") },
			{ ResourceType::AuditEvent_Entity_Detail, Str8Lit("AuditEvent_Entity_Detail") },
			{ ResourceType::Basic, Str8Lit("Basic") },
			{ ResourceType::Binary, Str8Lit("Binary") },
			{ ResourceType::BiologicallyDerivedProduct, Str8Lit("BiologicallyDerivedProduct") },
			{ ResourceType::BiologicallyDerivedProduct_Collection, Str8Lit("BiologicallyDerivedProduct_Collection") },
			{ ResourceType::BiologicallyDerivedProduct_Processing, Str8Lit("BiologicallyDerivedProduct_Processing") },
			{ ResourceType::BiologicallyDerivedProduct_Manipulation, Str8Lit("BiologicallyDerivedProduct_Manipulation") },
			{ ResourceType::BiologicallyDerivedProduct_Storage, Str8Lit("BiologicallyDerivedProduct_Storage") },
			{ ResourceType::BodyStructure, Str8Lit("BodyStructure") },
			{ ResourceType::Bundle, Str8Lit("Bundle") },
			{ ResourceType::Bundle_Link, Str8Lit("Bundle_Link") },
			{ ResourceType::Bundle_Entry, Str8Lit("Bundle_Entry") },
			{ ResourceType::Bundle_Entry_Search, Str8Lit("Bundle_Entry_Search") },
			{ ResourceType::Bundle_Entry_Request, Str8Lit("Bundle_Entry_Request") },
			{ ResourceType::Bundle_Entry_Response, Str8Lit("Bundle_Entry_Response") },
			{ ResourceType::CapabilityStatement, Str8Lit("CapabilityStatement") },
			{ ResourceType::CapabilityStatement_Software, Str8Lit("CapabilityStatement_Software") },
			{ ResourceType::CapabilityStatement_Implementation, Str8Lit("CapabilityStatement_Implementation") },
			{ ResourceType::CapabilityStatement_Rest, Str8Lit("CapabilityStatement_Rest") },
			{ ResourceType::CapabilityStatement_Rest_Security, Str8Lit("CapabilityStatement_Rest_Security") },
			{ ResourceType::CapabilityStatement_Rest_Resource, Str8Lit("CapabilityStatement_Rest_Resource") },
			{ ResourceType::CapabilityStatement_Rest_Resource_Interaction, Str8Lit("CapabilityStatement_Rest_Resource_Interaction") },
			{ ResourceType::CapabilityStatement_Rest_Resource_SearchParam, Str8Lit("CapabilityStatement_Rest_Resource_SearchParam") },
			{ ResourceType::CapabilityStatement_Rest_Resource_Operation, Str8Lit("CapabilityStatement_Rest_Resource_Operation") },
			{ ResourceType::CapabilityStatement_Rest_Interaction, Str8Lit("CapabilityStatement_Rest_Interaction") },
			{ ResourceType::CapabilityStatement_Messaging, Str8Lit("CapabilityStatement_Messaging") },
			{ ResourceType::CapabilityStatement_Messaging_Endpoint, Str8Lit("CapabilityStatement_Messaging_Endpoint") },
			{ ResourceType::CapabilityStatement_Messaging_SupportedMessage, Str8Lit("CapabilityStatement_Messaging_SupportedMessage") },
			{ ResourceType::CapabilityStatement_Document, Str8Lit("CapabilityStatement_Document") },
			{ ResourceType::CarePlan, Str8Lit("CarePlan") },
			{ ResourceType::CarePlan_Activity, Str8Lit("CarePlan_Activity") },
			{ ResourceType::CarePlan_Activity_Detail, Str8Lit("CarePlan_Activity_Detail") },
			{ ResourceType::CareTeam, Str8Lit("CareTeam") },
			{ ResourceType::CareTeam_Participant, Str8Lit("CareTeam_Participant") },
			{ ResourceType::CatalogEntry, Str8Lit("CatalogEntry") },
			{ ResourceType::CatalogEntry_RelatedEntry, Str8Lit("CatalogEntry_RelatedEntry") },
			{ ResourceType::ChargeItem, Str8Lit("ChargeItem") },
			{ ResourceType::ChargeItem_Performer, Str8Lit("ChargeItem_Performer") },
			{ ResourceType::ChargeItemDefinition, Str8Lit("ChargeItemDefinition") },
			{ ResourceType::ChargeItemDefinition_Applicability, Str8Lit("ChargeItemDefinition_Applicability") },
			{ ResourceType::ChargeItemDefinition_PropertyGroup, Str8Lit("ChargeItemDefinition_PropertyGroup") },
			{ ResourceType::ChargeItemDefinition_PropertyGroup_PriceComponent, Str8Lit("ChargeItemDefinition_PropertyGroup_PriceComponent") },
			{ ResourceType::Claim, Str8Lit("Claim") },
			{ ResourceType::Claim_Related, Str8Lit("Claim_Related") },
			{ ResourceType::Claim_Payee, Str8Lit("Claim_Payee") },
			{ ResourceType::Claim_CareTeam, Str8Lit("Claim_CareTeam") },
			{ ResourceType::Claim_SupportingInfo, Str8Lit("Claim_SupportingInfo") },
			{ ResourceType::Claim_Diagnosis, Str8Lit("Claim_Diagnosis") },
			{ ResourceType::Claim_Procedure, Str8Lit("Claim_Procedure") },
			{ ResourceType::Claim_Insurance, Str8Lit("Claim_Insurance") },
			{ ResourceType::Claim_Accident, Str8Lit("Claim_Accident") },
			{ ResourceType::Claim_Item, Str8Lit("Claim_Item") },
			{ ResourceType::Claim_Item_Detail, Str8Lit("Claim_Item_Detail") },
			{ ResourceType::Claim_Item_Detail_SubDetail, Str8Lit("Claim_Item_Detail_SubDetail") },
			{ ResourceType::ClaimResponse, Str8Lit("ClaimResponse") },
			{ ResourceType::ClaimResponse_Item, Str8Lit("ClaimResponse_Item") },
			{ ResourceType::ClaimResponse_Item_Adjudication, Str8Lit("ClaimResponse_Item_Adjudication") },
			{ ResourceType::ClaimResponse_Item_Detail, Str8Lit("ClaimResponse_Item_Detail") },
			{ ResourceType::ClaimResponse_Item_Detail_SubDetail, Str8Lit("ClaimResponse_Item_Detail_SubDetail") },
			{ ResourceType::ClaimResponse_AddItem, Str8Lit("ClaimResponse_AddItem") },
			{ ResourceType::ClaimResponse_AddItem_Detail, Str8Lit("ClaimResponse_AddItem_Detail") },
			{ ResourceType::ClaimResponse_AddItem_Detail_SubDetail, Str8Lit("ClaimResponse_AddItem_Detail_SubDetail") },
			{ ResourceType::ClaimResponse_Total, Str8Lit("ClaimResponse_Total") },
			{ ResourceType::ClaimResponse_Payment, Str8Lit("ClaimResponse_Payment") },
			{ ResourceType::ClaimResponse_ProcessNote, Str8Lit("ClaimResponse_ProcessNote") },
			{ ResourceType::ClaimResponse_Insurance, Str8Lit("ClaimResponse_Insurance") },
			{ ResourceType::ClaimResponse_Error, Str8Lit("ClaimResponse_Error") },
			{ ResourceType::ClinicalImpression, Str8Lit("ClinicalImpression") },
			{ ResourceType::ClinicalImpression_Investigation, Str8Lit("ClinicalImpression_Investigation") },
			{ ResourceType::ClinicalImpression_Finding, Str8Lit("ClinicalImpression_Finding") },
			{ ResourceType::CodeSystem, Str8Lit("CodeSystem") },
			{ ResourceType::CodeSystem_Filter, Str8Lit("CodeSystem_Filter") },
			{ ResourceType::CodeSystem_Property, Str8Lit("CodeSystem_Property") },
			{ ResourceType::CodeSystem_Concept, Str8Lit("CodeSystem_Concept") },
			{ ResourceType::CodeSystem_Concept_Designation, Str8Lit("CodeSystem_Concept_Designation") },
			{ ResourceType::CodeSystem_Concept_Property, Str8Lit("CodeSystem_Concept_Property") },
			{ ResourceType::Communication, Str8Lit("Communication") },
			{ ResourceType::Communication_Payload, Str8Lit("Communication_Payload") },
			{ ResourceType::CommunicationRequest, Str8Lit("CommunicationRequest") },
			{ ResourceType::CommunicationRequest_Payload, Str8Lit("CommunicationRequest_Payload") },
			{ ResourceType::CompartmentDefinition, Str8Lit("CompartmentDefinition") },
			{ ResourceType::CompartmentDefinition_Resource, Str8Lit("CompartmentDefinition_Resource") },
			{ ResourceType::Composition, Str8Lit("Composition") },
			{ ResourceType::Composition_Attester, Str8Lit("Composition_Attester") },
			{ ResourceType::Composition_RelatesTo, Str8Lit("Composition_RelatesTo") },
			{ ResourceType::Composition_Event, Str8Lit("Composition_Event") },
			{ ResourceType::Composition_Section, Str8Lit("Composition_Section") },
			{ ResourceType::ConceptMap, Str8Lit("ConceptMap") },
			{ ResourceType::ConceptMap_Group, Str8Lit("ConceptMap_Group") },
			{ ResourceType::ConceptMap_Group_Element, Str8Lit("ConceptMap_Group_Element") },
			{ ResourceType::ConceptMap_Group_Element_Target, Str8Lit("ConceptMap_Group_Element_Target") },
			{ ResourceType::ConceptMap_Group_Element_Target_DependsOn, Str8Lit("ConceptMap_Group_Element_Target_DependsOn") },
			{ ResourceType::ConceptMap_Group_Unmapped, Str8Lit("ConceptMap_Group_Unmapped") },
			{ ResourceType::Condition, Str8Lit("Condition") },
			{ ResourceType::Condition_Stage, Str8Lit("Condition_Stage") },
			{ ResourceType::Condition_Evidence, Str8Lit("Condition_Evidence") },
			{ ResourceType::Consent, Str8Lit("Consent") },
			{ ResourceType::Consent_Policy, Str8Lit("Consent_Policy") },
			{ ResourceType::Consent_Verification, Str8Lit("Consent_Verification") },
			{ ResourceType::Consent_Provision, Str8Lit("Consent_Provision") },
			{ ResourceType::Consent_Provision_Actor, Str8Lit("Consent_Provision_Actor") },
			{ ResourceType::Consent_Provision_Data, Str8Lit("Consent_Provision_Data") },
			{ ResourceType::Contract, Str8Lit("Contract") },
			{ ResourceType::Contract_ContentDefinition, Str8Lit("Contract_ContentDefinition") },
			{ ResourceType::Contract_Term, Str8Lit("Contract_Term") },
			{ ResourceType::Contract_Term_SecurityLabel, Str8Lit("Contract_Term_SecurityLabel") },
			{ ResourceType::Contract_Term_Offer, Str8Lit("Contract_Term_Offer") },
			{ ResourceType::Contract_Term_Offer_Party, Str8Lit("Contract_Term_Offer_Party") },
			{ ResourceType::Contract_Term_Offer_Answer, Str8Lit("Contract_Term_Offer_Answer") },
			{ ResourceType::Contract_Term_Asset, Str8Lit("Contract_Term_Asset") },
			{ ResourceType::Contract_Term_Asset_Context, Str8Lit("Contract_Term_Asset_Context") },
			{ ResourceType::Contract_Term_Asset_ValuedItem, Str8Lit("Contract_Term_Asset_ValuedItem") },
			{ ResourceType::Contract_Term_Action, Str8Lit("Contract_Term_Action") },
			{ ResourceType::Contract_Term_Action_Subject, Str8Lit("Contract_Term_Action_Subject") },
			{ ResourceType::Contract_Signer, Str8Lit("Contract_Signer") },
			{ ResourceType::Contract_Friendly, Str8Lit("Contract_Friendly") },
			{ ResourceType::Contract_Legal, Str8Lit("Contract_Legal") },
			{ ResourceType::Contract_Rule, Str8Lit("Contract_Rule") },
			{ ResourceType::Coverage, Str8Lit("Coverage") },
			{ ResourceType::Coverage_Class, Str8Lit("Coverage_Class") },
			{ ResourceType::Coverage_CostToBeneficiary, Str8Lit("Coverage_CostToBeneficiary") },
			{ ResourceType::Coverage_CostToBeneficiary_Exception, Str8Lit("Coverage_CostToBeneficiary_Exception") },
			{ ResourceType::CoverageEligibilityRequest, Str8Lit("CoverageEligibilityRequest") },
			{ ResourceType::CoverageEligibilityRequest_SupportingInfo, Str8Lit("CoverageEligibilityRequest_SupportingInfo") },
			{ ResourceType::CoverageEligibilityRequest_Insurance, Str8Lit("CoverageEligibilityRequest_Insurance") },
			{ ResourceType::CoverageEligibilityRequest_Item, Str8Lit("CoverageEligibilityRequest_Item") },
			{ ResourceType::CoverageEligibilityRequest_Item_Diagnosis, Str8Lit("CoverageEligibilityRequest_Item_Diagnosis") },
			{ ResourceType::CoverageEligibilityResponse, Str8Lit("CoverageEligibilityResponse") },
			{ ResourceType::CoverageEligibilityResponse_Insurance, Str8Lit("CoverageEligibilityResponse_Insurance") },
			{ ResourceType::CoverageEligibilityResponse_Insurance_Item, Str8Lit("CoverageEligibilityResponse_Insurance_Item") },
			{ ResourceType::CoverageEligibilityResponse_Insurance_Item_Benefit, Str8Lit("CoverageEligibilityResponse_Insurance_Item_Benefit") },
			{ ResourceType::CoverageEligibilityResponse_Error, Str8Lit("CoverageEligibilityResponse_Error") },
			{ ResourceType::DetectedIssue, Str8Lit("DetectedIssue") },
			{ ResourceType::DetectedIssue_Evidence, Str8Lit("DetectedIssue_Evidence") },
			{ ResourceType::DetectedIssue_Mitigation, Str8Lit("DetectedIssue_Mitigation") },
			{ ResourceType::Device, Str8Lit("Device") },
			{ ResourceType::Device_UdiCarrier, Str8Lit("Device_UdiCarrier") },
			{ ResourceType::Device_DeviceName, Str8Lit("Device_DeviceName") },
			{ ResourceType::Device_Specialization, Str8Lit("Device_Specialization") },
			{ ResourceType::Device_Version, Str8Lit("Device_Version") },
			{ ResourceType::Device_Property, Str8Lit("Device_Property") },
			{ ResourceType::DeviceDefinition, Str8Lit("DeviceDefinition") },
			{ ResourceType::DeviceDefinition_UdiDeviceIdentifier, Str8Lit("DeviceDefinition_UdiDeviceIdentifier") },
			{ ResourceType::DeviceDefinition_DeviceName, Str8Lit("DeviceDefinition_DeviceName") },
			{ ResourceType::DeviceDefinition_Specialization, Str8Lit("DeviceDefinition_Specialization") },
			{ ResourceType::DeviceDefinition_Capability, Str8Lit("DeviceDefinition_Capability") },
			{ ResourceType::DeviceDefinition_Property, Str8Lit("DeviceDefinition_Property") },
			{ ResourceType::DeviceDefinition_Material, Str8Lit("DeviceDefinition_Material") },
			{ ResourceType::DeviceMetric, Str8Lit("DeviceMetric") },
			{ ResourceType::DeviceMetric_Calibration, Str8Lit("DeviceMetric_Calibration") },
			{ ResourceType::DeviceRequest, Str8Lit("DeviceRequest") },
			{ ResourceType::DeviceRequest_Parameter, Str8Lit("DeviceRequest_Parameter") },
			{ ResourceType::DeviceUseStatement, Str8Lit("DeviceUseStatement") },
			{ ResourceType::DiagnosticReport, Str8Lit("DiagnosticReport") },
			{ ResourceType::DiagnosticReport_Media, Str8Lit("DiagnosticReport_Media") },
			{ ResourceType::DocumentManifest, Str8Lit("DocumentManifest") },
			{ ResourceType::DocumentManifest_Related, Str8Lit("DocumentManifest_Related") },
			{ ResourceType::DocumentReference, Str8Lit("DocumentReference") },
			{ ResourceType::DocumentReference_RelatesTo, Str8Lit("DocumentReference_RelatesTo") },
			{ ResourceType::DocumentReference_Content, Str8Lit("DocumentReference_Content") },
			{ ResourceType::DocumentReference_Context, Str8Lit("DocumentReference_Context") },
			{ ResourceType::DomainResource, Str8Lit("DomainResource") },
			{ ResourceType::EffectEvidenceSynthesis, Str8Lit("EffectEvidenceSynthesis") },
			{ ResourceType::EffectEvidenceSynthesis_SampleSize, Str8Lit("EffectEvidenceSynthesis_SampleSize") },
			{ ResourceType::EffectEvidenceSynthesis_ResultsByExposure, Str8Lit("EffectEvidenceSynthesis_ResultsByExposure") },
			{ ResourceType::EffectEvidenceSynthesis_EffectEstimate, Str8Lit("EffectEvidenceSynthesis_EffectEstimate") },
			{ ResourceType::EffectEvidenceSynthesis_EffectEstimate_PrecisionEstimate, Str8Lit("EffectEvidenceSynthesis_EffectEstimate_PrecisionEstimate") },
			{ ResourceType::EffectEvidenceSynthesis_Certainty, Str8Lit("EffectEvidenceSynthesis_Certainty") },
			{ ResourceType::EffectEvidenceSynthesis_Certainty_CertaintySubcomponent, Str8Lit("EffectEvidenceSynthesis_Certainty_CertaintySubcomponent") },
			{ ResourceType::Encounter, Str8Lit("Encounter") },
			{ ResourceType::Encounter_StatusHistory, Str8Lit("Encounter_StatusHistory") },
			{ ResourceType::Encounter_ClassHistory, Str8Lit("Encounter_ClassHistory") },
			{ ResourceType::Encounter_Participant, Str8Lit("Encounter_Participant") },
			{ ResourceType::Encounter_Diagnosis, Str8Lit("Encounter_Diagnosis") },
			{ ResourceType::Encounter_Hospitalization, Str8Lit("Encounter_Hospitalization") },
			{ ResourceType::Encounter_Location, Str8Lit("Encounter_Location") },
			{ ResourceType::Endpoint, Str8Lit("Endpoint") },
			{ ResourceType::EnrollmentRequest, Str8Lit("EnrollmentRequest") },
			{ ResourceType::EnrollmentResponse, Str8Lit("EnrollmentResponse") },
			{ ResourceType::EpisodeOfCare, Str8Lit("EpisodeOfCare") },
			{ ResourceType::EpisodeOfCare_StatusHistory, Str8Lit("EpisodeOfCare_StatusHistory") },
			{ ResourceType::EpisodeOfCare_Diagnosis, Str8Lit("EpisodeOfCare_Diagnosis") },
			{ ResourceType::EventDefinition, Str8Lit("EventDefinition") },
			{ ResourceType::Evidence, Str8Lit("Evidence") },
			{ ResourceType::EvidenceVariable, Str8Lit("EvidenceVariable") },
			{ ResourceType::EvidenceVariable_Characteristic, Str8Lit("EvidenceVariable_Characteristic") },
			{ ResourceType::ExampleScenario, Str8Lit("ExampleScenario") },
			{ ResourceType::ExampleScenario_Actor, Str8Lit("ExampleScenario_Actor") },
			{ ResourceType::ExampleScenario_Instance, Str8Lit("ExampleScenario_Instance") },
			{ ResourceType::ExampleScenario_Instance_Version, Str8Lit("ExampleScenario_Instance_Version") },
			{ ResourceType::ExampleScenario_Instance_ContainedInstance, Str8Lit("ExampleScenario_Instance_ContainedInstance") },
			{ ResourceType::ExampleScenario_Process, Str8Lit("ExampleScenario_Process") },
			{ ResourceType::ExampleScenario_Process_Step, Str8Lit("ExampleScenario_Process_Step") },
			{ ResourceType::ExampleScenario_Process_Step_Operation, Str8Lit("ExampleScenario_Process_Step_Operation") },
			{ ResourceType::ExampleScenario_Process_Step_Alternative, Str8Lit("ExampleScenario_Process_Step_Alternative") },
			{ ResourceType::ExplanationOfBenefit, Str8Lit("ExplanationOfBenefit") },
			{ ResourceType::ExplanationOfBenefit_Related, Str8Lit("ExplanationOfBenefit_Related") },
			{ ResourceType::ExplanationOfBenefit_Payee, Str8Lit("ExplanationOfBenefit_Payee") },
			{ ResourceType::ExplanationOfBenefit_CareTeam, Str8Lit("ExplanationOfBenefit_CareTeam") },
			{ ResourceType::ExplanationOfBenefit_SupportingInfo, Str8Lit("ExplanationOfBenefit_SupportingInfo") },
			{ ResourceType::ExplanationOfBenefit_Diagnosis, Str8Lit("ExplanationOfBenefit_Diagnosis") },
			{ ResourceType::ExplanationOfBenefit_Procedure, Str8Lit("ExplanationOfBenefit_Procedure") },
			{ ResourceType::ExplanationOfBenefit_Insurance, Str8Lit("ExplanationOfBenefit_Insurance") },
			{ ResourceType::ExplanationOfBenefit_Accident, Str8Lit("ExplanationOfBenefit_Accident") },
			{ ResourceType::ExplanationOfBenefit_Item, Str8Lit("ExplanationOfBenefit_Item") },
			{ ResourceType::ExplanationOfBenefit_Item_Adjudication, Str8Lit("ExplanationOfBenefit_Item_Adjudication") },
			{ ResourceType::ExplanationOfBenefit_Item_Detail, Str8Lit("ExplanationOfBenefit_Item_Detail") },
			{ ResourceType::ExplanationOfBenefit_Item_Detail_SubDetail, Str8Lit("ExplanationOfBenefit_Item_Detail_SubDetail") },
			{ ResourceType::ExplanationOfBenefit_AddItem, Str8Lit("ExplanationOfBenefit_AddItem") },
			{ ResourceType::ExplanationOfBenefit_AddItem_Detail, Str8Lit("ExplanationOfBenefit_AddItem_Detail") },
			{ ResourceType::ExplanationOfBenefit_AddItem_Detail_SubDetail, Str8Lit("ExplanationOfBenefit_AddItem_Detail_SubDetail") },
			{ ResourceType::ExplanationOfBenefit_Total, Str8Lit("ExplanationOfBenefit_Total") },
			{ ResourceType::ExplanationOfBenefit_Payment, Str8Lit("ExplanationOfBenefit_Payment") },
			{ ResourceType::ExplanationOfBenefit_ProcessNote, Str8Lit("ExplanationOfBenefit_ProcessNote") },
			{ ResourceType::ExplanationOfBenefit_BenefitBalance, Str8Lit("ExplanationOfBenefit_BenefitBalance") },
			{ ResourceType::ExplanationOfBenefit_BenefitBalance_Financial, Str8Lit("ExplanationOfBenefit_BenefitBalance_Financial") },
			{ ResourceType::FamilyMemberHistory, Str8Lit("FamilyMemberHistory") },
			{ ResourceType::FamilyMemberHistory_Condition, Str8Lit("FamilyMemberHistory_Condition") },
			{ ResourceType::Flag, Str8Lit("Flag") },
			{ ResourceType::Goal, Str8Lit("Goal") },
			{ ResourceType::Goal_Target, Str8Lit("Goal_Target") },
			{ ResourceType::GraphDefinition, Str8Lit("GraphDefinition") },
			{ ResourceType::GraphDefinition_Link, Str8Lit("GraphDefinition_Link") },
			{ ResourceType::GraphDefinition_Link_Target, Str8Lit("GraphDefinition_Link_Target") },
			{ ResourceType::GraphDefinition_Link_Target_Compartment, Str8Lit("GraphDefinition_Link_Target_Compartment") },
			{ ResourceType::Group, Str8Lit("Group") },
			{ ResourceType::Group_Characteristic, Str8Lit("Group_Characteristic") },
			{ ResourceType::Group_Member, Str8Lit("Group_Member") },
			{ ResourceType::GuidanceResponse, Str8Lit("GuidanceResponse") },
			{ ResourceType::HealthcareService, Str8Lit("HealthcareService") },
			{ ResourceType::HealthcareService_Eligibility, Str8Lit("HealthcareService_Eligibility") },
			{ ResourceType::HealthcareService_AvailableTime, Str8Lit("HealthcareService_AvailableTime") },
			{ ResourceType::HealthcareService_NotAvailable, Str8Lit("HealthcareService_NotAvailable") },
			{ ResourceType::ImagingStudy, Str8Lit("ImagingStudy") },
			{ ResourceType::ImagingStudy_Series, Str8Lit("ImagingStudy_Series") },
			{ ResourceType::ImagingStudy_Series_Performer, Str8Lit("ImagingStudy_Series_Performer") },
			{ ResourceType::ImagingStudy_Series_Instance, Str8Lit("ImagingStudy_Series_Instance") },
			{ ResourceType::Immunization, Str8Lit("Immunization") },
			{ ResourceType::Immunization_Performer, Str8Lit("Immunization_Performer") },
			{ ResourceType::Immunization_Education, Str8Lit("Immunization_Education") },
			{ ResourceType::Immunization_Reaction, Str8Lit("Immunization_Reaction") },
			{ ResourceType::Immunization_ProtocolApplied, Str8Lit("Immunization_ProtocolApplied") },
			{ ResourceType::ImmunizationEvaluation, Str8Lit("ImmunizationEvaluation") },
			{ ResourceType::ImmunizationRecommendation, Str8Lit("ImmunizationRecommendation") },
			{ ResourceType::ImmunizationRecommendation_Recommendation, Str8Lit("ImmunizationRecommendation_Recommendation") },
			{ ResourceType::ImmunizationRecommendation_Recommendation_DateCriterion, Str8Lit("ImmunizationRecommendation_Recommendation_DateCriterion") },
			{ ResourceType::ImplementationGuide, Str8Lit("ImplementationGuide") },
			{ ResourceType::ImplementationGuide_DependsOn, Str8Lit("ImplementationGuide_DependsOn") },
			{ ResourceType::ImplementationGuide_Global, Str8Lit("ImplementationGuide_Global") },
			{ ResourceType::ImplementationGuide_Definition, Str8Lit("ImplementationGuide_Definition") },
			{ ResourceType::ImplementationGuide_Definition_Grouping, Str8Lit("ImplementationGuide_Definition_Grouping") },
			{ ResourceType::ImplementationGuide_Definition_Resource, Str8Lit("ImplementationGuide_Definition_Resource") },
			{ ResourceType::ImplementationGuide_Definition_Page, Str8Lit("ImplementationGuide_Definition_Page") },
			{ ResourceType::ImplementationGuide_Definition_Parameter, Str8Lit("ImplementationGuide_Definition_Parameter") },
			{ ResourceType::ImplementationGuide_Definition_Template, Str8Lit("ImplementationGuide_Definition_Template") },
			{ ResourceType::ImplementationGuide_Manifest, Str8Lit("ImplementationGuide_Manifest") },
			{ ResourceType::ImplementationGuide_Manifest_Resource, Str8Lit("ImplementationGuide_Manifest_Resource") },
			{ ResourceType::ImplementationGuide_Manifest_Page, Str8Lit("ImplementationGuide_Manifest_Page") },
			{ ResourceType::InsurancePlan, Str8Lit("InsurancePlan") },
			{ ResourceType::InsurancePlan_Contact, Str8Lit("InsurancePlan_Contact") },
			{ ResourceType::InsurancePlan_Coverage, Str8Lit("InsurancePlan_Coverage") },
			{ ResourceType::InsurancePlan_Coverage_Benefit, Str8Lit("InsurancePlan_Coverage_Benefit") },
			{ ResourceType::InsurancePlan_Coverage_Benefit_Limit, Str8Lit("InsurancePlan_Coverage_Benefit_Limit") },
			{ ResourceType::InsurancePlan_Plan, Str8Lit("InsurancePlan_Plan") },
			{ ResourceType::InsurancePlan_Plan_GeneralCost, Str8Lit("InsurancePlan_Plan_GeneralCost") },
			{ ResourceType::InsurancePlan_Plan_SpecificCost, Str8Lit("InsurancePlan_Plan_SpecificCost") },
			{ ResourceType::InsurancePlan_Plan_SpecificCost_Benefit, Str8Lit("InsurancePlan_Plan_SpecificCost_Benefit") },
			{ ResourceType::InsurancePlan_Plan_SpecificCost_Benefit_Cost, Str8Lit("InsurancePlan_Plan_SpecificCost_Benefit_Cost") },
			{ ResourceType::Invoice, Str8Lit("Invoice") },
			{ ResourceType::Invoice_Participant, Str8Lit("Invoice_Participant") },
			{ ResourceType::Invoice_LineItem, Str8Lit("Invoice_LineItem") },
			{ ResourceType::Invoice_LineItem_PriceComponent, Str8Lit("Invoice_LineItem_PriceComponent") },
			{ ResourceType::Library, Str8Lit("Library") },
			{ ResourceType::Linkage, Str8Lit("Linkage") },
			{ ResourceType::Linkage_Item, Str8Lit("Linkage_Item") },
			{ ResourceType::List, Str8Lit("List") },
			{ ResourceType::List_Entry, Str8Lit("List_Entry") },
			{ ResourceType::Location, Str8Lit("Location") },
			{ ResourceType::Location_Position, Str8Lit("Location_Position") },
			{ ResourceType::Location_HoursOfOperation, Str8Lit("Location_HoursOfOperation") },
			{ ResourceType::Measure, Str8Lit("Measure") },
			{ ResourceType::Measure_Group, Str8Lit("Measure_Group") },
			{ ResourceType::Measure_Group_Population, Str8Lit("Measure_Group_Population") },
			{ ResourceType::Measure_Group_Stratifier, Str8Lit("Measure_Group_Stratifier") },
			{ ResourceType::Measure_Group_Stratifier_Component, Str8Lit("Measure_Group_Stratifier_Component") },
			{ ResourceType::Measure_SupplementalData, Str8Lit("Measure_SupplementalData") },
			{ ResourceType::MeasureReport, Str8Lit("MeasureReport") },
			{ ResourceType::MeasureReport_Group, Str8Lit("MeasureReport_Group") },
			{ ResourceType::MeasureReport_Group_Population, Str8Lit("MeasureReport_Group_Population") },
			{ ResourceType::MeasureReport_Group_Stratifier, Str8Lit("MeasureReport_Group_Stratifier") },
			{ ResourceType::MeasureReport_Group_Stratifier_Stratum, Str8Lit("MeasureReport_Group_Stratifier_Stratum") },
			{ ResourceType::MeasureReport_Group_Stratifier_Stratum_Component, Str8Lit("MeasureReport_Group_Stratifier_Stratum_Component") },
			{ ResourceType::MeasureReport_Group_Stratifier_Stratum_Population, Str8Lit("MeasureReport_Group_Stratifier_Stratum_Population") },
			{ ResourceType::Media, Str8Lit("Media") },
			{ ResourceType::Medication, Str8Lit("Medication") },
			{ ResourceType::Medication_Ingredient, Str8Lit("Medication_Ingredient") },
			{ ResourceType::Medication_Batch, Str8Lit("Medication_Batch") },
			{ ResourceType::MedicationAdministration, Str8Lit("MedicationAdministration") },
			{ ResourceType::MedicationAdministration_Performer, Str8Lit("MedicationAdministration_Performer") },
			{ ResourceType::MedicationAdministration_Dosage, Str8Lit("MedicationAdministration_Dosage") },
			{ ResourceType::MedicationDispense, Str8Lit("MedicationDispense") },
			{ ResourceType::MedicationDispense_Performer, Str8Lit("MedicationDispense_Performer") },
			{ ResourceType::MedicationDispense_Substitution, Str8Lit("MedicationDispense_Substitution") },
			{ ResourceType::MedicationKnowledge, Str8Lit("MedicationKnowledge") },
			{ ResourceType::MedicationKnowledge_RelatedMedicationKnowledge, Str8Lit("MedicationKnowledge_RelatedMedicationKnowledge") },
			{ ResourceType::MedicationKnowledge_Monograph, Str8Lit("MedicationKnowledge_Monograph") },
			{ ResourceType::MedicationKnowledge_Ingredient, Str8Lit("MedicationKnowledge_Ingredient") },
			{ ResourceType::MedicationKnowledge_Cost, Str8Lit("MedicationKnowledge_Cost") },
			{ ResourceType::MedicationKnowledge_MonitoringProgram, Str8Lit("MedicationKnowledge_MonitoringProgram") },
			{ ResourceType::MedicationKnowledge_AdministrationGuidelines, Str8Lit("MedicationKnowledge_AdministrationGuidelines") },
			{ ResourceType::MedicationKnowledge_AdministrationGuidelines_Dosage, Str8Lit("MedicationKnowledge_AdministrationGuidelines_Dosage") },
			{ ResourceType::MedicationKnowledge_AdministrationGuidelines_PatientCharacteristics, Str8Lit("MedicationKnowledge_AdministrationGuidelines_PatientCharacteristics") },
			{ ResourceType::MedicationKnowledge_MedicineClassification, Str8Lit("MedicationKnowledge_MedicineClassification") },
			{ ResourceType::MedicationKnowledge_Packaging, Str8Lit("MedicationKnowledge_Packaging") },
			{ ResourceType::MedicationKnowledge_DrugCharacteristic, Str8Lit("MedicationKnowledge_DrugCharacteristic") },
			{ ResourceType::MedicationKnowledge_Regulatory, Str8Lit("MedicationKnowledge_Regulatory") },
			{ ResourceType::MedicationKnowledge_Regulatory_Substitution, Str8Lit("MedicationKnowledge_Regulatory_Substitution") },
			{ ResourceType::MedicationKnowledge_Regulatory_Schedule, Str8Lit("MedicationKnowledge_Regulatory_Schedule") },
			{ ResourceType::MedicationKnowledge_Regulatory_MaxDispense, Str8Lit("MedicationKnowledge_Regulatory_MaxDispense") },
			{ ResourceType::MedicationKnowledge_Kinetics, Str8Lit("MedicationKnowledge_Kinetics") },
			{ ResourceType::MedicationRequest, Str8Lit("MedicationRequest") },
			{ ResourceType::MedicationRequest_DispenseRequest, Str8Lit("MedicationRequest_DispenseRequest") },
			{ ResourceType::MedicationRequest_DispenseRequest_InitialFill, Str8Lit("MedicationRequest_DispenseRequest_InitialFill") },
			{ ResourceType::MedicationRequest_Substitution, Str8Lit("MedicationRequest_Substitution") },
			{ ResourceType::MedicationStatement, Str8Lit("MedicationStatement") },
			{ ResourceType::MedicinalProduct, Str8Lit("MedicinalProduct") },
			{ ResourceType::MedicinalProduct_Name, Str8Lit("MedicinalProduct_Name") },
			{ ResourceType::MedicinalProduct_Name_NamePart, Str8Lit("MedicinalProduct_Name_NamePart") },
			{ ResourceType::MedicinalProduct_Name_CountryLanguage, Str8Lit("MedicinalProduct_Name_CountryLanguage") },
			{ ResourceType::MedicinalProduct_ManufacturingBusinessOperation, Str8Lit("MedicinalProduct_ManufacturingBusinessOperation") },
			{ ResourceType::MedicinalProduct_SpecialDesignation, Str8Lit("MedicinalProduct_SpecialDesignation") },
			{ ResourceType::MedicinalProductAuthorization, Str8Lit("MedicinalProductAuthorization") },
			{ ResourceType::MedicinalProductAuthorization_JurisdictionalAuthorization, Str8Lit("MedicinalProductAuthorization_JurisdictionalAuthorization") },
			{ ResourceType::MedicinalProductAuthorization_Procedure, Str8Lit("MedicinalProductAuthorization_Procedure") },
			{ ResourceType::MedicinalProductContraindication, Str8Lit("MedicinalProductContraindication") },
			{ ResourceType::MedicinalProductContraindication_OtherTherapy, Str8Lit("MedicinalProductContraindication_OtherTherapy") },
			{ ResourceType::MedicinalProductIndication, Str8Lit("MedicinalProductIndication") },
			{ ResourceType::MedicinalProductIndication_OtherTherapy, Str8Lit("MedicinalProductIndication_OtherTherapy") },
			{ ResourceType::MedicinalProductIngredient, Str8Lit("MedicinalProductIngredient") },
			{ ResourceType::MedicinalProductIngredient_SpecifiedSubstance, Str8Lit("MedicinalProductIngredient_SpecifiedSubstance") },
			{ ResourceType::MedicinalProductIngredient_SpecifiedSubstance_Strength, Str8Lit("MedicinalProductIngredient_SpecifiedSubstance_Strength") },
			{ ResourceType::MedicinalProductIngredient_SpecifiedSubstance_Strength_ReferenceStrength, Str8Lit("MedicinalProductIngredient_SpecifiedSubstance_Strength_ReferenceStrength") },
			{ ResourceType::MedicinalProductIngredient_Substance, Str8Lit("MedicinalProductIngredient_Substance") },
			{ ResourceType::MedicinalProductInteraction, Str8Lit("MedicinalProductInteraction") },
			{ ResourceType::MedicinalProductInteraction_Interactant, Str8Lit("MedicinalProductInteraction_Interactant") },
			{ ResourceType::MedicinalProductManufactured, Str8Lit("MedicinalProductManufactured") },
			{ ResourceType::MedicinalProductPackaged, Str8Lit("MedicinalProductPackaged") },
			{ ResourceType::MedicinalProductPackaged_BatchIdentifier, Str8Lit("MedicinalProductPackaged_BatchIdentifier") },
			{ ResourceType::MedicinalProductPackaged_PackageItem, Str8Lit("MedicinalProductPackaged_PackageItem") },
			{ ResourceType::MedicinalProductPharmaceutical, Str8Lit("MedicinalProductPharmaceutical") },
			{ ResourceType::MedicinalProductPharmaceutical_Characteristics, Str8Lit("MedicinalProductPharmaceutical_Characteristics") },
			{ ResourceType::MedicinalProductPharmaceutical_RouteOfAdministration, Str8Lit("MedicinalProductPharmaceutical_RouteOfAdministration") },
			{ ResourceType::MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies, Str8Lit("MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies") },
			{ ResourceType::MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies_WithdrawalPeriod, Str8Lit("MedicinalProductPharmaceutical_RouteOfAdministration_TargetSpecies_WithdrawalPeriod") },
			{ ResourceType::MedicinalProductUndesirableEffect, Str8Lit("MedicinalProductUndesirableEffect") },
			{ ResourceType::MessageDefinition, Str8Lit("MessageDefinition") },
			{ ResourceType::MessageDefinition_Focus, Str8Lit("MessageDefinition_Focus") },
			{ ResourceType::MessageDefinition_AllowedResponse, Str8Lit("MessageDefinition_AllowedResponse") },
			{ ResourceType::MessageHeader, Str8Lit("MessageHeader") },
			{ ResourceType::MessageHeader_Destination, Str8Lit("MessageHeader_Destination") },
			{ ResourceType::MessageHeader_Source, Str8Lit("MessageHeader_Source") },
			{ ResourceType::MessageHeader_Response, Str8Lit("MessageHeader_Response") },
			{ ResourceType::MolecularSequence, Str8Lit("MolecularSequence") },
			{ ResourceType::MolecularSequence_ReferenceSeq, Str8Lit("MolecularSequence_ReferenceSeq") },
			{ ResourceType::MolecularSequence_Variant, Str8Lit("MolecularSequence_Variant") },
			{ ResourceType::MolecularSequence_Quality, Str8Lit("MolecularSequence_Quality") },
			{ ResourceType::MolecularSequence_Quality_Roc, Str8Lit("MolecularSequence_Quality_Roc") },
			{ ResourceType::MolecularSequence_Repository, Str8Lit("MolecularSequence_Repository") },
			{ ResourceType::MolecularSequence_StructureVariant, Str8Lit("MolecularSequence_StructureVariant") },
			{ ResourceType::MolecularSequence_StructureVariant_Outer, Str8Lit("MolecularSequence_StructureVariant_Outer") },
			{ ResourceType::MolecularSequence_StructureVariant_Inner, Str8Lit("MolecularSequence_StructureVariant_Inner") },
			{ ResourceType::NamingSystem, Str8Lit("NamingSystem") },
			{ ResourceType::NamingSystem_UniqueId, Str8Lit("NamingSystem_UniqueId") },
			{ ResourceType::NutritionOrder, Str8Lit("NutritionOrder") },
			{ ResourceType::NutritionOrder_OralDiet, Str8Lit("NutritionOrder_OralDiet") },
			{ ResourceType::NutritionOrder_OralDiet_Nutrient, Str8Lit("NutritionOrder_OralDiet_Nutrient") },
			{ ResourceType::NutritionOrder_OralDiet_Texture, Str8Lit("NutritionOrder_OralDiet_Texture") },
			{ ResourceType::NutritionOrder_Supplement, Str8Lit("NutritionOrder_Supplement") },
			{ ResourceType::NutritionOrder_EnteralFormula, Str8Lit("NutritionOrder_EnteralFormula") },
			{ ResourceType::NutritionOrder_EnteralFormula_Administration, Str8Lit("NutritionOrder_EnteralFormula_Administration") },
			{ ResourceType::Observation, Str8Lit("Observation") },
			{ ResourceType::Observation_ReferenceRange, Str8Lit("Observation_ReferenceRange") },
			{ ResourceType::Observation_Component, Str8Lit("Observation_Component") },
			{ ResourceType::ObservationDefinition, Str8Lit("ObservationDefinition") },
			{ ResourceType::ObservationDefinition_QuantitativeDetails, Str8Lit("ObservationDefinition_QuantitativeDetails") },
			{ ResourceType::ObservationDefinition_QualifiedInterval, Str8Lit("ObservationDefinition_QualifiedInterval") },
			{ ResourceType::OperationDefinition, Str8Lit("OperationDefinition") },
			{ ResourceType::OperationDefinition_Parameter, Str8Lit("OperationDefinition_Parameter") },
			{ ResourceType::OperationDefinition_Parameter_Binding, Str8Lit("OperationDefinition_Parameter_Binding") },
			{ ResourceType::OperationDefinition_Parameter_ReferencedFrom, Str8Lit("OperationDefinition_Parameter_ReferencedFrom") },
			{ ResourceType::OperationDefinition_Overload, Str8Lit("OperationDefinition_Overload") },
			{ ResourceType::OperationOutcome, Str8Lit("OperationOutcome") },
			{ ResourceType::OperationOutcome_Issue, Str8Lit("OperationOutcome_Issue") },
			{ ResourceType::Organization, Str8Lit("Organization") },
			{ ResourceType::Organization_Contact, Str8Lit("Organization_Contact") },
			{ ResourceType::OrganizationAffiliation, Str8Lit("OrganizationAffiliation") },
			{ ResourceType::Parameters, Str8Lit("Parameters") },
			{ ResourceType::Parameters_Parameter, Str8Lit("Parameters_Parameter") },
			{ ResourceType::Patient, Str8Lit("Patient") },
			{ ResourceType::Patient_Contact, Str8Lit("Patient_Contact") },
			{ ResourceType::Patient_Communication, Str8Lit("Patient_Communication") },
			{ ResourceType::Patient_Link, Str8Lit("Patient_Link") },
			{ ResourceType::PaymentNotice, Str8Lit("PaymentNotice") },
			{ ResourceType::PaymentReconciliation, Str8Lit("PaymentReconciliation") },
			{ ResourceType::PaymentReconciliation_Detail, Str8Lit("PaymentReconciliation_Detail") },
			{ ResourceType::PaymentReconciliation_ProcessNote, Str8Lit("PaymentReconciliation_ProcessNote") },
			{ ResourceType::Person, Str8Lit("Person") },
			{ ResourceType::Person_Link, Str8Lit("Person_Link") },
			{ ResourceType::PlanDefinition, Str8Lit("PlanDefinition") },
			{ ResourceType::PlanDefinition_Goal, Str8Lit("PlanDefinition_Goal") },
			{ ResourceType::PlanDefinition_Goal_Target, Str8Lit("PlanDefinition_Goal_Target") },
			{ ResourceType::PlanDefinition_Action, Str8Lit("PlanDefinition_Action") },
			{ ResourceType::PlanDefinition_Action_Condition, Str8Lit("PlanDefinition_Action_Condition") },
			{ ResourceType::PlanDefinition_Action_RelatedAction, Str8Lit("PlanDefinition_Action_RelatedAction") },
			{ ResourceType::PlanDefinition_Action_Participant, Str8Lit("PlanDefinition_Action_Participant") },
			{ ResourceType::PlanDefinition_Action_DynamicValue, Str8Lit("PlanDefinition_Action_DynamicValue") },
			{ ResourceType::Practitioner, Str8Lit("Practitioner") },
			{ ResourceType::Practitioner_Qualification, Str8Lit("Practitioner_Qualification") },
			{ ResourceType::PractitionerRole, Str8Lit("PractitionerRole") },
			{ ResourceType::PractitionerRole_AvailableTime, Str8Lit("PractitionerRole_AvailableTime") },
			{ ResourceType::PractitionerRole_NotAvailable, Str8Lit("PractitionerRole_NotAvailable") },
			{ ResourceType::Procedure, Str8Lit("Procedure") },
			{ ResourceType::Procedure_Performer, Str8Lit("Procedure_Performer") },
			{ ResourceType::Procedure_FocalDevice, Str8Lit("Procedure_FocalDevice") },
			{ ResourceType::Provenance, Str8Lit("Provenance") },
			{ ResourceType::Provenance_Agent, Str8Lit("Provenance_Agent") },
			{ ResourceType::Provenance_Entity, Str8Lit("Provenance_Entity") },
			{ ResourceType::Questionnaire, Str8Lit("Questionnaire") },
			{ ResourceType::Questionnaire_Item, Str8Lit("Questionnaire_Item") },
			{ ResourceType::Questionnaire_Item_EnableWhen, Str8Lit("Questionnaire_Item_EnableWhen") },
			{ ResourceType::Questionnaire_Item_AnswerOption, Str8Lit("Questionnaire_Item_AnswerOption") },
			{ ResourceType::Questionnaire_Item_Initial, Str8Lit("Questionnaire_Item_Initial") },
			{ ResourceType::QuestionnaireResponse, Str8Lit("QuestionnaireResponse") },
			{ ResourceType::QuestionnaireResponse_Item, Str8Lit("QuestionnaireResponse_Item") },
			{ ResourceType::QuestionnaireResponse_Item_Answer, Str8Lit("QuestionnaireResponse_Item_Answer") },
			{ ResourceType::RelatedPerson, Str8Lit("RelatedPerson") },
			{ ResourceType::RelatedPerson_Communication, Str8Lit("RelatedPerson_Communication") },
			{ ResourceType::RequestGroup, Str8Lit("RequestGroup") },
			{ ResourceType::RequestGroup_Action, Str8Lit("RequestGroup_Action") },
			{ ResourceType::RequestGroup_Action_Condition, Str8Lit("RequestGroup_Action_Condition") },
			{ ResourceType::RequestGroup_Action_RelatedAction, Str8Lit("RequestGroup_Action_RelatedAction") },
			{ ResourceType::ResearchDefinition, Str8Lit("ResearchDefinition") },
			{ ResourceType::ResearchElementDefinition, Str8Lit("ResearchElementDefinition") },
			{ ResourceType::ResearchElementDefinition_Characteristic, Str8Lit("ResearchElementDefinition_Characteristic") },
			{ ResourceType::ResearchStudy, Str8Lit("ResearchStudy") },
			{ ResourceType::ResearchStudy_Arm, Str8Lit("ResearchStudy_Arm") },
			{ ResourceType::ResearchStudy_Objective, Str8Lit("ResearchStudy_Objective") },
			{ ResourceType::ResearchSubject, Str8Lit("ResearchSubject") },
			{ ResourceType::RiskAssessment, Str8Lit("RiskAssessment") },
			{ ResourceType::RiskAssessment_Prediction, Str8Lit("RiskAssessment_Prediction") },
			{ ResourceType::RiskEvidenceSynthesis, Str8Lit("RiskEvidenceSynthesis") },
			{ ResourceType::RiskEvidenceSynthesis_SampleSize, Str8Lit("RiskEvidenceSynthesis_SampleSize") },
			{ ResourceType::RiskEvidenceSynthesis_RiskEstimate, Str8Lit("RiskEvidenceSynthesis_RiskEstimate") },
			{ ResourceType::RiskEvidenceSynthesis_RiskEstimate_PrecisionEstimate, Str8Lit("RiskEvidenceSynthesis_RiskEstimate_PrecisionEstimate") },
			{ ResourceType::RiskEvidenceSynthesis_Certainty, Str8Lit("RiskEvidenceSynthesis_Certainty") },
			{ ResourceType::RiskEvidenceSynthesis_Certainty_CertaintySubcomponent, Str8Lit("RiskEvidenceSynthesis_Certainty_CertaintySubcomponent") },
			{ ResourceType::Schedule, Str8Lit("Schedule") },
			{ ResourceType::SearchParameter, Str8Lit("SearchParameter") },
			{ ResourceType::SearchParameter_Component, Str8Lit("SearchParameter_Component") },
			{ ResourceType::ServiceRequest, Str8Lit("ServiceRequest") },
			{ ResourceType::Slot, Str8Lit("Slot") },
			{ ResourceType::Specimen, Str8Lit("Specimen") },
			{ ResourceType::Specimen_Collection, Str8Lit("Specimen_Collection") },
			{ ResourceType::Specimen_Processing, Str8Lit("Specimen_Processing") },
			{ ResourceType::Specimen_Container, Str8Lit("Specimen_Container") },
			{ ResourceType::SpecimenDefinition, Str8Lit("SpecimenDefinition") },
			{ ResourceType::SpecimenDefinition_TypeTested, Str8Lit("SpecimenDefinition_TypeTested") },
			{ ResourceType::SpecimenDefinition_TypeTested_Container, Str8Lit("SpecimenDefinition_TypeTested_Container") },
			{ ResourceType::SpecimenDefinition_TypeTested_Container_Additive, Str8Lit("SpecimenDefinition_TypeTested_Container_Additive") },
			{ ResourceType::SpecimenDefinition_TypeTested_Handling, Str8Lit("SpecimenDefinition_TypeTested_Handling") },
			{ ResourceType::StructureDefinition, Str8Lit("StructureDefinition") },
			{ ResourceType::StructureDefinition_Mapping, Str8Lit("StructureDefinition_Mapping") },
			{ ResourceType::StructureDefinition_Context, Str8Lit("StructureDefinition_Context") },
			{ ResourceType::StructureDefinition_Snapshot, Str8Lit("StructureDefinition_Snapshot") },
			{ ResourceType::StructureDefinition_Differential, Str8Lit("StructureDefinition_Differential") },
			{ ResourceType::StructureMap, Str8Lit("StructureMap") },
			{ ResourceType::StructureMap_Structure, Str8Lit("StructureMap_Structure") },
			{ ResourceType::StructureMap_Group, Str8Lit("StructureMap_Group") },
			{ ResourceType::StructureMap_Group_Input, Str8Lit("StructureMap_Group_Input") },
			{ ResourceType::StructureMap_Group_Rule, Str8Lit("StructureMap_Group_Rule") },
			{ ResourceType::StructureMap_Group_Rule_Source, Str8Lit("StructureMap_Group_Rule_Source") },
			{ ResourceType::StructureMap_Group_Rule_Target, Str8Lit("StructureMap_Group_Rule_Target") },
			{ ResourceType::StructureMap_Group_Rule_Target_Parameter, Str8Lit("StructureMap_Group_Rule_Target_Parameter") },
			{ ResourceType::StructureMap_Group_Rule_Dependent, Str8Lit("StructureMap_Group_Rule_Dependent") },
			{ ResourceType::Subscription, Str8Lit("Subscription") },
			{ ResourceType::Subscription_Channel, Str8Lit("Subscription_Channel") },
			{ ResourceType::Substance, Str8Lit("Substance") },
			{ ResourceType::Substance_Instance, Str8Lit("Substance_Instance") },
			{ ResourceType::Substance_Ingredient, Str8Lit("Substance_Ingredient") },
			{ ResourceType::SubstanceNucleicAcid, Str8Lit("SubstanceNucleicAcid") },
			{ ResourceType::SubstanceNucleicAcid_Subunit, Str8Lit("SubstanceNucleicAcid_Subunit") },
			{ ResourceType::SubstanceNucleicAcid_Subunit_Linkage, Str8Lit("SubstanceNucleicAcid_Subunit_Linkage") },
			{ ResourceType::SubstanceNucleicAcid_Subunit_Sugar, Str8Lit("SubstanceNucleicAcid_Subunit_Sugar") },
			{ ResourceType::SubstancePolymer, Str8Lit("SubstancePolymer") },
			{ ResourceType::SubstancePolymer_MonomerSet, Str8Lit("SubstancePolymer_MonomerSet") },
			{ ResourceType::SubstancePolymer_MonomerSet_StartingMaterial, Str8Lit("SubstancePolymer_MonomerSet_StartingMaterial") },
			{ ResourceType::SubstancePolymer_Repeat, Str8Lit("SubstancePolymer_Repeat") },
			{ ResourceType::SubstancePolymer_Repeat_RepeatUnit, Str8Lit("SubstancePolymer_Repeat_RepeatUnit") },
			{ ResourceType::SubstancePolymer_Repeat_RepeatUnit_DegreeOfPolymerisation, Str8Lit("SubstancePolymer_Repeat_RepeatUnit_DegreeOfPolymerisation") },
			{ ResourceType::SubstancePolymer_Repeat_RepeatUnit_StructuralRepresentation, Str8Lit("SubstancePolymer_Repeat_RepeatUnit_StructuralRepresentation") },
			{ ResourceType::SubstanceProtein, Str8Lit("SubstanceProtein") },
			{ ResourceType::SubstanceProtein_Subunit, Str8Lit("SubstanceProtein_Subunit") },
			{ ResourceType::SubstanceReferenceInformation, Str8Lit("SubstanceReferenceInformation") },
			{ ResourceType::SubstanceReferenceInformation_Gene, Str8Lit("SubstanceReferenceInformation_Gene") },
			{ ResourceType::SubstanceReferenceInformation_GeneElement, Str8Lit("SubstanceReferenceInformation_GeneElement") },
			{ ResourceType::SubstanceReferenceInformation_Classification, Str8Lit("SubstanceReferenceInformation_Classification") },
			{ ResourceType::SubstanceReferenceInformation_Target, Str8Lit("SubstanceReferenceInformation_Target") },
			{ ResourceType::SubstanceSourceMaterial, Str8Lit("SubstanceSourceMaterial") },
			{ ResourceType::SubstanceSourceMaterial_FractionDescription, Str8Lit("SubstanceSourceMaterial_FractionDescription") },
			{ ResourceType::SubstanceSourceMaterial_Organism, Str8Lit("SubstanceSourceMaterial_Organism") },
			{ ResourceType::SubstanceSourceMaterial_Organism_Author, Str8Lit("SubstanceSourceMaterial_Organism_Author") },
			{ ResourceType::SubstanceSourceMaterial_Organism_Hybrid, Str8Lit("SubstanceSourceMaterial_Organism_Hybrid") },
			{ ResourceType::SubstanceSourceMaterial_Organism_OrganismGeneral, Str8Lit("SubstanceSourceMaterial_Organism_OrganismGeneral") },
			{ ResourceType::SubstanceSourceMaterial_PartDescription, Str8Lit("SubstanceSourceMaterial_PartDescription") },
			{ ResourceType::SubstanceSpecification, Str8Lit("SubstanceSpecification") },
			{ ResourceType::SubstanceSpecification_Moiety, Str8Lit("SubstanceSpecification_Moiety") },
			{ ResourceType::SubstanceSpecification_Property, Str8Lit("SubstanceSpecification_Property") },
			{ ResourceType::SubstanceSpecification_Structure, Str8Lit("SubstanceSpecification_Structure") },
			{ ResourceType::SubstanceSpecification_Structure_Isotope, Str8Lit("SubstanceSpecification_Structure_Isotope") },
			{ ResourceType::SubstanceSpecification_Structure_Isotope_MolecularWeight, Str8Lit("SubstanceSpecification_Structure_Isotope_MolecularWeight") },
			{ ResourceType::SubstanceSpecification_Structure_Representation, Str8Lit("SubstanceSpecification_Structure_Representation") },
			{ ResourceType::SubstanceSpecification_Code, Str8Lit("SubstanceSpecification_Code") },
			{ ResourceType::SubstanceSpecification_Name, Str8Lit("SubstanceSpecification_Name") },
			{ ResourceType::SubstanceSpecification_Name_Official, Str8Lit("SubstanceSpecification_Name_Official") },
			{ ResourceType::SubstanceSpecification_Relationship, Str8Lit("SubstanceSpecification_Relationship") },
			{ ResourceType::SupplyDelivery, Str8Lit("SupplyDelivery") },
			{ ResourceType::SupplyDelivery_SuppliedItem, Str8Lit("SupplyDelivery_SuppliedItem") },
			{ ResourceType::SupplyRequest, Str8Lit("SupplyRequest") },
			{ ResourceType::SupplyRequest_Parameter, Str8Lit("SupplyRequest_Parameter") },
			{ ResourceType::Task, Str8Lit("Task") },
			{ ResourceType::Task_Restriction, Str8Lit("Task_Restriction") },
			{ ResourceType::Task_Input, Str8Lit("Task_Input") },
			{ ResourceType::Task_Output, Str8Lit("Task_Output") },
			{ ResourceType::TerminologyCapabilities, Str8Lit("TerminologyCapabilities") },
			{ ResourceType::TerminologyCapabilities_Software, Str8Lit("TerminologyCapabilities_Software") },
			{ ResourceType::TerminologyCapabilities_Implementation, Str8Lit("TerminologyCapabilities_Implementation") },
			{ ResourceType::TerminologyCapabilities_CodeSystem, Str8Lit("TerminologyCapabilities_CodeSystem") },
			{ ResourceType::TerminologyCapabilities_CodeSystem_Version, Str8Lit("TerminologyCapabilities_CodeSystem_Version") },
			{ ResourceType::TerminologyCapabilities_CodeSystem_Version_Filter, Str8Lit("TerminologyCapabilities_CodeSystem_Version_Filter") },
			{ ResourceType::TerminologyCapabilities_Expansion, Str8Lit("TerminologyCapabilities_Expansion") },
			{ ResourceType::TerminologyCapabilities_Expansion_Parameter, Str8Lit("TerminologyCapabilities_Expansion_Parameter") },
			{ ResourceType::TerminologyCapabilities_ValidateCode, Str8Lit("TerminologyCapabilities_ValidateCode") },
			{ ResourceType::TerminologyCapabilities_Translation, Str8Lit("TerminologyCapabilities_Translation") },
			{ ResourceType::TerminologyCapabilities_Closure, Str8Lit("TerminologyCapabilities_Closure") },
			{ ResourceType::TestReport, Str8Lit("TestReport") },
			{ ResourceType::TestReport_Participant, Str8Lit("TestReport_Participant") },
			{ ResourceType::TestReport_Setup, Str8Lit("TestReport_Setup") },
			{ ResourceType::TestReport_Setup_Action, Str8Lit("TestReport_Setup_Action") },
			{ ResourceType::TestReport_Setup_Action_Operation, Str8Lit("TestReport_Setup_Action_Operation") },
			{ ResourceType::TestReport_Setup_Action_Assert, Str8Lit("TestReport_Setup_Action_Assert") },
			{ ResourceType::TestReport_Test, Str8Lit("TestReport_Test") },
			{ ResourceType::TestReport_Test_Action, Str8Lit("TestReport_Test_Action") },
			{ ResourceType::TestReport_Teardown, Str8Lit("TestReport_Teardown") },
			{ ResourceType::TestReport_Teardown_Action, Str8Lit("TestReport_Teardown_Action") },
			{ ResourceType::TestScript, Str8Lit("TestScript") },
			{ ResourceType::TestScript_Origin, Str8Lit("TestScript_Origin") },
			{ ResourceType::TestScript_Destination, Str8Lit("TestScript_Destination") },
			{ ResourceType::TestScript_Metadata, Str8Lit("TestScript_Metadata") },
			{ ResourceType::TestScript_Metadata_Link, Str8Lit("TestScript_Metadata_Link") },
			{ ResourceType::TestScript_Metadata_Capability, Str8Lit("TestScript_Metadata_Capability") },
			{ ResourceType::TestScript_Fixture, Str8Lit("TestScript_Fixture") },
			{ ResourceType::TestScript_Variable, Str8Lit("TestScript_Variable") },
			{ ResourceType::TestScript_Setup, Str8Lit("TestScript_Setup") },
			{ ResourceType::TestScript_Setup_Action, Str8Lit("TestScript_Setup_Action") },
			{ ResourceType::TestScript_Setup_Action_Operation, Str8Lit("TestScript_Setup_Action_Operation") },
			{ ResourceType::TestScript_Setup_Action_Operation_RequestHeader, Str8Lit("TestScript_Setup_Action_Operation_RequestHeader") },
			{ ResourceType::TestScript_Setup_Action_Assert, Str8Lit("TestScript_Setup_Action_Assert") },
			{ ResourceType::TestScript_Test, Str8Lit("TestScript_Test") },
			{ ResourceType::TestScript_Test_Action, Str8Lit("TestScript_Test_Action") },
			{ ResourceType::TestScript_Teardown, Str8Lit("TestScript_Teardown") },
			{ ResourceType::TestScript_Teardown_Action, Str8Lit("TestScript_Teardown_Action") },
			{ ResourceType::ValueSet, Str8Lit("ValueSet") },
			{ ResourceType::ValueSet_Compose, Str8Lit("ValueSet_Compose") },
			{ ResourceType::ValueSet_Compose_Include, Str8Lit("ValueSet_Compose_Include") },
			{ ResourceType::ValueSet_Compose_Include_Concept, Str8Lit("ValueSet_Compose_Include_Concept") },
			{ ResourceType::ValueSet_Compose_Include_Concept_Designation, Str8Lit("ValueSet_Compose_Include_Concept_Designation") },
			{ ResourceType::ValueSet_Compose_Include_Filter, Str8Lit("ValueSet_Compose_Include_Filter") },
			{ ResourceType::ValueSet_Expansion, Str8Lit("ValueSet_Expansion") },
			{ ResourceType::ValueSet_Expansion_Parameter, Str8Lit("ValueSet_Expansion_Parameter") },
			{ ResourceType::ValueSet_Expansion_Contains, Str8Lit("ValueSet_Expansion_Contains") },
			{ ResourceType::VerificationResult, Str8Lit("VerificationResult") },
			{ ResourceType::VerificationResult_PrimarySource, Str8Lit("VerificationResult_PrimarySource") },
			{ ResourceType::VerificationResult_Attestation, Str8Lit("VerificationResult_Attestation") },
			{ ResourceType::VerificationResult_Validator, Str8Lit("VerificationResult_Validator") },
			{ ResourceType::VisionPrescription, Str8Lit("VisionPrescription") },
			{ ResourceType::VisionPrescription_LensSpecification, Str8Lit("VisionPrescription_LensSpecification") },
			{ ResourceType::VisionPrescription_LensSpecification_Prism, Str8Lit("VisionPrescription_LensSpecification_Prism") },
			{ ResourceType::MetadataResource, Str8Lit("MetadataResource") },
			{ ResourceType::Element, Str8Lit("Element") },
			{ ResourceType::BackboneElement, Str8Lit("BackboneElement") },
			{ ResourceType::Address, Str8Lit("Address") },
			{ ResourceType::Age, Str8Lit("Age") },
			{ ResourceType::Annotation, Str8Lit("Annotation") },
			{ ResourceType::Attachment, Str8Lit("Attachment") },
			{ ResourceType::CodeableConcept, Str8Lit("CodeableConcept") },
			{ ResourceType::Coding, Str8Lit("Coding") },
			{ ResourceType::ContactDetail, Str8Lit("ContactDetail") },
			{ ResourceType::ContactPoint, Str8Lit("ContactPoint") },
			{ ResourceType::Contributor, Str8Lit("Contributor") },
			{ ResourceType::Count, Str8Lit("Count") },
			{ ResourceType::DataRequirement, Str8Lit("DataRequirement") },
			{ ResourceType::DataRequirement_CodeFilter, Str8Lit("DataRequirement_CodeFilter") },
			{ ResourceType::DataRequirement_DateFilter, Str8Lit("DataRequirement_DateFilter") },
			{ ResourceType::DataRequirement_Sort, Str8Lit("DataRequirement_Sort") },
			{ ResourceType::Distance, Str8Lit("Distance") },
			{ ResourceType::Dosage, Str8Lit("Dosage") },
			{ ResourceType::Dosage_DoseAndRate, Str8Lit("Dosage_DoseAndRate") },
			{ ResourceType::Duration, Str8Lit("Duration") },
			{ ResourceType::ElementDefinition, Str8Lit("ElementDefinition") },
			{ ResourceType::ElementDefinition_Slicing, Str8Lit("ElementDefinition_Slicing") },
			{ ResourceType::ElementDefinition_Slicing_Discriminator, Str8Lit("ElementDefinition_Slicing_Discriminator") },
			{ ResourceType::ElementDefinition_Base, Str8Lit("ElementDefinition_Base") },
			{ ResourceType::ElementDefinition_Type, Str8Lit("ElementDefinition_Type") },
			{ ResourceType::ElementDefinition_Example, Str8Lit("ElementDefinition_Example") },
			{ ResourceType::ElementDefinition_Constraint, Str8Lit("ElementDefinition_Constraint") },
			{ ResourceType::ElementDefinition_Binding, Str8Lit("ElementDefinition_Binding") },
			{ ResourceType::ElementDefinition_Mapping, Str8Lit("ElementDefinition_Mapping") },
			{ ResourceType::Expression, Str8Lit("Expression") },
			{ ResourceType::Extension, Str8Lit("Extension") },
			{ ResourceType::HumanName, Str8Lit("HumanName") },
			{ ResourceType::Identifier, Str8Lit("Identifier") },
			{ ResourceType::MarketingStatus, Str8Lit("MarketingStatus") },
			{ ResourceType::Meta, Str8Lit("Meta") },
			{ ResourceType::Money, Str8Lit("Money") },
			{ ResourceType::Narrative, Str8Lit("Narrative") },
			{ ResourceType::ParameterDefinition, Str8Lit("ParameterDefinition") },
			{ ResourceType::Period, Str8Lit("Period") },
			{ ResourceType::Population, Str8Lit("Population") },
			{ ResourceType::ProdCharacteristic, Str8Lit("ProdCharacteristic") },
			{ ResourceType::ProductShelfLife, Str8Lit("ProductShelfLife") },
			{ ResourceType::Quantity, Str8Lit("Quantity") },
			{ ResourceType::Range, Str8Lit("Range") },
			{ ResourceType::Ratio, Str8Lit("Ratio") },
			{ ResourceType::Reference, Str8Lit("Reference") },
			{ ResourceType::RelatedArtifact, Str8Lit("RelatedArtifact") },
			{ ResourceType::SampledData, Str8Lit("SampledData") },
			{ ResourceType::Signature, Str8Lit("Signature") },
			{ ResourceType::SubstanceAmount, Str8Lit("SubstanceAmount") },
			{ ResourceType::SubstanceAmount_ReferenceRange, Str8Lit("SubstanceAmount_ReferenceRange") },
			{ ResourceType::Timing, Str8Lit("Timing") },
			{ ResourceType::Timing_Repeat, Str8Lit("Timing_Repeat") },
			{ ResourceType::TriggerDefinition, Str8Lit("TriggerDefinition") },
			{ ResourceType::UsageContext, Str8Lit("UsageContext") },
			{ ResourceType::MoneyQuantity, Str8Lit("MoneyQuantity") },
			{ ResourceType::SimpleQuantity, Str8Lit("SimpleQuantity") },
			{ ResourceType::Shareablemeasure, Str8Lit("Shareablemeasure") },
			{ ResourceType::Servicerequest_genetics, Str8Lit("Servicerequest_genetics") },
			{ ResourceType::Groupdefinition, Str8Lit("Groupdefinition") },
			{ ResourceType::Actualgroup, Str8Lit("Actualgroup") },
			{ ResourceType::Familymemberhistory_genetic, Str8Lit("Familymemberhistory_genetic") },
			{ ResourceType::Shareableactivitydefinition, Str8Lit("Shareableactivitydefinition") },
			{ ResourceType::Cdshooksrequestgroup, Str8Lit("Cdshooksrequestgroup") },
			{ ResourceType::Provenance_relevant_history, Str8Lit("Provenance_relevant_history") },
			{ ResourceType::Cqf_questionnaire, Str8Lit("Cqf_questionnaire") },
			{ ResourceType::Shareablevalueset, Str8Lit("Shareablevalueset") },
			{ ResourceType::Picoelement, Str8Lit("Picoelement") },
			{ ResourceType::Shareablecodesystem, Str8Lit("Shareablecodesystem") },
			{ ResourceType::Cdshooksguidanceresponse, Str8Lit("Cdshooksguidanceresponse") },
			{ ResourceType::Devicemetricobservation, Str8Lit("Devicemetricobservation") },
			{ ResourceType::Observation_genetics, Str8Lit("Observation_genetics") },
			{ ResourceType::Vitalsigns, Str8Lit("Vitalsigns") },
			{ ResourceType::Bodyweight, Str8Lit("Bodyweight") },
			{ ResourceType::Vitalspanel, Str8Lit("Vitalspanel") },
			{ ResourceType::Bodyheight, Str8Lit("Bodyheight") },
			{ ResourceType::Resprate, Str8Lit("Resprate") },
			{ ResourceType::Heartrate, Str8Lit("Heartrate") },
			{ ResourceType::Bodytemp, Str8Lit("Bodytemp") },
			{ ResourceType::Headcircum, Str8Lit("Headcircum") },
			{ ResourceType::Oxygensat, Str8Lit("Oxygensat") },
			{ ResourceType::Bmi, Str8Lit("Bmi") },
			{ ResourceType::Bp, Str8Lit("Bp") },
			{ ResourceType::Shareablelibrary, Str8Lit("Shareablelibrary") },
			{ ResourceType::Cqllibrary, Str8Lit("Cqllibrary") },
			{ ResourceType::Lipidprofile, Str8Lit("Lipidprofile") },
			{ ResourceType::Cholesterol, Str8Lit("Cholesterol") },
			{ ResourceType::Triglyceride, Str8Lit("Triglyceride") },
			{ ResourceType::Hdlcholesterol, Str8Lit("Hdlcholesterol") },
			{ ResourceType::Ldlcholesterol, Str8Lit("Ldlcholesterol") },
			{ ResourceType::Diagnosticreport_genetics, Str8Lit("Diagnosticreport_genetics") },
			{ ResourceType::Hlaresult, Str8Lit("Hlaresult") },
			{ ResourceType::Synthesis, Str8Lit("Synthesis") },
			{ ResourceType::Clinicaldocument, Str8Lit("Clinicaldocument") },
			{ ResourceType::Catalog, Str8Lit("Catalog") },
			{ ResourceType::Shareableplandefinition, Str8Lit("Shareableplandefinition") },
			{ ResourceType::Computableplandefinition, Str8Lit("Computableplandefinition") },
			{ ResourceType::Cdshooksserviceplandefinition, Str8Lit("Cdshooksserviceplandefinition") },
			{ ResourceType::Elementdefinition_de, Str8Lit("Elementdefinition_de") },
			{ ResourceType::Ehrsrle_auditevent, Str8Lit("Ehrsrle_auditevent") },
			{ ResourceType::Ehrsrle_provenance, Str8Lit("Ehrsrle_provenance") },
		};
	};
};
#endif